version: '2'
services:

  web:
    image: "daocloud.io/sanzuwu/tieba-cloud-sign:latest"
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWD: janejane123456
      DB_NAME: tiebacloud
      CSRF: "false"
    ports:
      - "6006:8080"
    links:
      - db
    depends_on:
      - db
    
  db:
    image: "mysql:5.5"
    environment:
      MYSQL_DATABASE: tiebacloud
      MYSQL_ROOT_PASSWORD: janejane123456
    volumes:
      - /sharedfolders/appdata/tieba-cloud-sign/mysql:/var/lib/mysql
